### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by josedom24** [codeforspain/datos#1]
Hola, soy profesor de FP de informática, y doy un módulo de "Lenguajes de marcas". Realmente es muy complicado encontrar datos abiertos en España y la iniciativa me parece muy buena.
Buscando por mis apuntes he encontrado datos sobre provincias y municipios:
https://dl.dropboxusercontent.com/u/620873/provinciasypoblaciones.xml.zip
¿Este tipo de datos es lo que estáis buscando?
Un saludo

**Comment by jalbertoroman** [comment]
Gracias Jose, si esa es la idea! 
Intentaremos añadir shapefiles (las geometrías), algo así: 
![screenshot 2016-04-06 13 11 20](https://cloud.githubusercontent.com/assets/18272734/14314716/3777eff2-fbf9-11e5-836d-a2e5815e4311.png)
