### ISSUE TITLE
Licencias de las fuentes que cojamos

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#10]
Tema espinoso. Hay muchos sitios donde la licencia no está clara o es propietaria. Pero son datos públicos. ¿Los cogemos igualmente y ponemos nuestra licencia abierta? ¿o descartamos esa fuente? ¿Qué experiencias tenéis?

**Comment by amfeli** [comment]
Hice una consulta hace un par de años a los servicios jurídicos de mi universidad (Exttremadura) y lo que me dijeron es que solo se pueden redistribuir aquellos datos que tengan una licencia explícita que lo permita. Cuando no hay licencia no se puede, no es lo mismo usar que redistribuir.

**Comment by fesja** [comment]
@amfeli la duda que tengo es si esos datos son públicos. Yo lo consulté para una startup que tuve, y los datos públicos tipo coordenadas, nombre, dirección, teléfono, etc se consideran de interés general y por tanto puedes usarlos como quieras por mucho que las licencias digan lo contrario. 

Quizás tengamos que ver fuente por fuente, pero si son de un organismo público seguramente podamos considerarlo dato público. Esperamos más feedback!

**Comment by amfeli** [comment]
Es que una cosa es usar y otra redistribuir, es diferente.

**Comment by inigoflores** [comment]
Licencia para el Catastro:

http://www.catastro.minhap.es/pdf/ovc/licdescargaES.pdf

> 6.Se autoriza el uso público, incluido el comercial, de la información catastral que
> haya sido sometida a cualquier proceso previo de transformación, en los términos
> establecidos en el artículo 21, Real Decreto Legislativo 1/1996, de 12 de abril, por el
> que se aprueba el texto refundido de la Ley de Propiedad Intelectual. Solo existirá
> transformación de la información catastral si su traducción, adaptación o cualquier
> otra modificación en su forma da lugar a una obra diferente.
> La transformación de la información catastral no podrá suponer alteración del
> contenido de la información original ni desnaturalización de su sentido (artículo 8. a)
> y b) de la Ley 37/2007) 

Me pregunto sí la difusión de los datos transformados a otro formato que no sea el original encaja con lo mencionado en este artículo.

**Comment by iblancasa** [comment]
Siempre que no se especifique que lo datos sean libres no podemos usarlos. No tiene más.

En cuanto a lo que escribe @inigoflores, creo que sí podríamos reutilizarlos (no estaríamos desvirtualizando los datos, se estaría creando una obra nueva -creo- y no se estarían alterando los datos)

**Comment by fesja** [comment]
Decisión tomada: Solo usaremos aquellas fuentes que permitan la redistribución de sus datos.

Para aquellas fuentes que no lo permitan, intentaremos hablar con sus propietarios para que nos den permiso de redistribución.

**Comment by jgsogo** [comment]
Para las fuentes que no permitan la redistribución se hace aún más necesario el enfoque de proporcionar un script (#8, #9) para que cada uno pueda automatizar el proceso de descargárselos y reformatearlos desde la fuente original. Y que sea cada uno y el uso que haga de esos datos el que tenga que lidiar con la licencia.

(Siento postear en un hilo cerrado, pero vais demasiado rápido ^^)
