### ISSUE TITLE
Experiencias con iniciativas parecidas a esta

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#11]
Abro este hilo para que los que habéis participado en iniciativas de este estilo, nos comentéis qué funcionó y que se puede mejorar.

**Comment by calonso** [comment]
Buenas, yo he colaborado durante un año o así con OpenCorporates. Ellos organizaban [meetups mensuales](http://www.meetup.com/London-Open-Data-Missions/) en la que todo aquel que quería colaborar iba, ayudaba a 'scrapear' algún data source y ya de paso se tomaba unas cerves, unas patatas fritas o similares y conocía gente.

Creo que organizar una meetup similar puede ser una gran idea para atraer colaboradores y trabajar juntos en un mismo espacio todos juntos de vez en cuando.

**Comment by amfeli** [comment]
Hay cientos de repositorios de datos, a veces completamente libres, otras con algunas limitaciones (uso comercial bajo autorización, por ejemplo). Refiriéndonos a España exclusivamente, el lugar más importante es http://centrodedescargas.cnig.es/CentroDescargas/cambiarMenu.do?destino=presentacion En general estos repositorios son conocidos como IDE, Infraestructuras de Datos Espaciales. Tanto a nivel nacional como autonómico (y a veces menor), se puede encontrar un listado en http://idee.es/ En la Universidad de Extremadura organicé un sistema similar que podeis ver en http://secad.unex.es/conocimiento/

**Comment by fesja** [comment]
@calonso esos meetups estaban más pensados en orientar y dar charlas o en sacar resultados? Porque en 2-4h no da tiempo a mucho. ¿Recuerdas qué hiciste en alguno por ejemplo?

Estoy a favor de hacer meetups, pero no deberían ser solo en Madrid/Barcelona. Es decir, que los que vivan fuera también puedan estar en meetups virtuales y no se sientan excluidos.

@amfeli he movido esos enlaces al wiki!

**Comment by calonso** [comment]
@fesja El objetivo de los meetups era darse a conocer y 'reclutar' voluntarios, trabajar juntos y poco a poco ir sacando resultados (scrapers, visualizaciones, etc...). Es cierto que en 2-4 horas no da tiempo a mucho, pero tampoco había que terminarlo de una vez, de hecho yo tardé casi 5 meetups en hacer uno de mis scrapers.

Respecto de los meetups tienes toda la razón, cuantos más haya mejor. Inicialmente creo que con tener uno en Madrid y/o Barcelona sería suficiente, ir aprendiendo y dar la posibilidad de unirse virtualmente a aquellos que no vivan en esa(s) ciudades hasta que vayan saliendo grupos de gente en otras ciudades para hacer sus propios meetups.

**Comment by amfeli** [comment]
Otro repositorio de propósito general
Nature Scientific Data  http://www.nature.com/sdata/

**Comment by fesja** [comment]
@calonso tiene sentido! Habrá que organizarlos :)

**Comment by aloaisa** [comment]
Muy buenas!
 Junto con otros amigos tenemos unos pocos scrappers que hicimos para un projecto openSource de búsqueda de empleo con las fuentes de datos que proporciona la Junta de Castilla y león.

Os podríamos pasar el código de los scrappers si os vienen bien.

Salu2!

**Comment by fesja** [comment]
Poned los enlaces en el wiki! Asi puede resultar interesante a alguien.
Gracias!

2016-04-10 21:17 GMT+02:00 Alvaro Garcia Loaisa notifications@github.com:

**Comment by fpedrera** [comment]
Hola.

Creo que puedes encontrar cosas en común con Pro Bono Público (http://blog.probp.org/), OKF Spain (http://okfn.es/), Civio (http://www.civio.es/), LocaliData (http://localidata.com/), Fundación CTIC (http://www.fundacionctic.org/lineas-de-especializacion/interoperabilidad-od?gclid=CKHXkKSchswCFfgW0wod1IEFkQ) o el nodo en Madrid de Open Data Institute (https://theodi.org/nodes/madrid), además de otras organizaciones que ya se han mencionado como el IGN.

En OKF hay una lista de correo abierta, seguramente haya simpatizantes de tu iniciativa entre sus socios.
