### ISSUE TITLE
Requisitos para publicar datos

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#12]
He redactado una pequeña guía de los requisitos que creo que deberíamos exigirnos de cara a enlazar o publicar datos bajo el paraguas de Code For Spain.

https://github.com/codeforspain/datos/wiki/Requisitos-para-publicar-datos

¿Creéis que algún punto sobra o falta algo?

**Comment by inigoflores** [comment]
De acuerdo en todo. 

Algunos comentarios:
- **La fuente original permite la redistribución de los datos.**
  
  Hay que aclarar exactamente qué significa "Publicar Datos":
  - Descarga y redistribución de los datos sin transformar.
  - Descarga y redistribución de los datos transformados.
  - Publicación de herramientas para la descarga de los datos.
  
  Ya hemos mencionado que algunos datos no vamos a redistribuirlos (por tamaño, limitación de licencia, etc.), pero sí que van a tener su propia sección en el catálogo, donde se incluirá información acerca de la fuente, junto con las herramientas para la descarga/consulta.
  
  Por lo tanto, el tema de la licencia es quizás secundario, en cuanto a que proporcionar herramientas no implica _redistribución_ (serán los usuarios los que descargarán los datos directamente de la fuente).
- **Los datos deben estar en formato CSV, JSON y GeoJSON.**
  
  Convertir de JSON a CSV es sencillo. Ej. http://konklone.io/json/ . Incluso de JSON a XML (y viceversa). Siempre se pueden ofrecer varias opciones de descarga a partir de nuestra copia local en JSON. 
  
  Supongo que GeoJSON es solo relevante para datos geográficos.
