### ISSUE TITLE
Diseñar y maquetar landing page

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#13]
Buenas!

Podríamos hacer una landing muy básica en codeforspain.org donde captar interesados y que puedan:
- Visitar este repo de Github
- Unirse al canal de Slack automáticamente
- Unirse a la newsletter

Podríamos reaprovechar esto https://github.com/rauchg/slackin y modificarlo un poco o hacerlo desde cero (no veo preferencia). Realmente es una landing muy básica con un script básico que añada el email via API a Slack y a Mailchimp. Yo puedo alojarla.

**¿Algún diseñador se anima a hacerla y un developer a maquetarla?** ¿Se os ocurre algo más a meter ahora?

Una vez ya tengamos fuentes de datos, ya la complicaremos.

**Comment by iblancasa** [comment]
Yo tiraría por algo más visual. Tal vez hecho con Polymer: se hace rápido, es bonito y viene bien adaptado para móviles y esas cosas (además que trae muchos módulos para hacer cosas chulas).

Para alojarla podemos Github pages.

**Comment by jorgeatgu** [comment]
@fesja Contad conmigo para maquetarla, para diseñarla seguro que hay gente que lo hace mejor :)

@iblancasa Me parece un poco lío meter Polymer para algo tan básico, tiraría por algo más normal que se pueda mantener en el tiempo.

**Comment by iblancasa** [comment]
@jorgeatgu yo precisamente lo veo más sencillo por que es nada más que ir añadiendo módulos, pero lo que veáis.

**Comment by enriquebv** [comment]
@fesja Aquí otro dispuesto a maquetarla en cuanto este listo el diseño. Opino igual que @jorgeatgu, algo de lio hacerla con Polymer, ya que al ser una landing "básica" supongo que bastara con escribir solo lo que se necesite.

**Comment by fesja** [comment]
@jorgeatgu @bit-dev @iblancasa vamos entonces sin polymer; os paso luego un diseño básico. Para cuando tengamos ya los primeros 10 datasets intentaremos convencer a un diseñador de que nos ayude :)

**Comment by fesja** [comment]
Os comparto una posible landing sencillita. Creo que es suficiente hasta que tengamos los datasets y tengamos algo más que mostrar. Quitando el logo, que ocultaremos el mapa, ¿cómo veis el resto? ¿Suficiente?

![landing](https://cloud.githubusercontent.com/assets/10658/14477881/2b5317d4-0111-11e6-9ce2-ef1b16b7be69.png)

**Comment by javaguirre** [comment]
A mí me gusta la landing, es concisa y expone claramente los objetivos.

**Comment by fesja** [comment]
wow, @jorgeatgu [ya la ha maquetado](https://github.com/codeforspain/datos/pull/20)!! Gracias!

Jorge, he creado el repo https://github.com/codeforspain/landing-page donde podemos meter la web, asi dejamos este solo para índice de los datos. El logo pon uno cualquiera y ya hago yo el cambio cuando la suba.

**Comment by jorgeatgu** [comment]
Perfecto @fesja ya he subido la landing al repo de landing :)

@iblancasa @bit-dev podemos ir abriendo issues en ese repo para iniciar un debate sobre que podemos usar SASS, LESS, postCSS, BEM etc...

**Comment by martgnz** [comment]
El dominio, cuál será? Algo como codefor.es?

Para más adelante, a mí me gusta mucho la web de la iniciativa alemana: http://codefor.de

**Comment by enriquebv** [comment]
Buen trabajo @jorgeatgu ;)
[He hecho](https://github.com/codeforspain/landing-page/pull/2) un par de correcciones en los textos y añadido un poco de CSS para que el diseño sea lo mas parecido posible al de la imagen.

**Comment by fesja** [comment]
@martgnz el dominio que tengo es www.codeforspain.org
@bit-dev nice!

**Comment by fesja** [comment]
ya he subido la landing! http://www.codeforspain.org/
