### ISSUE TITLE
Mejor forma para estar al tanto de lo que se avanza en Code For Spain

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#14]
Ahora mismo tenemos los siguientes canales de comunicación:
- Este Github
- Slack
- [Twitter](https://twitter.com/codeforspain)

Todos aquí estamos de voluntarios, estamos porque nos apetece. Algunos estaremos más atentos y otros menos. La pregunta que me hago es cual es la mejor manera de que la mayoría de nosotros estemos al tanto de lo que se avanza en Code For Spain.

Me da la impresión de que algo estilo newsletter puede ser una buena manera de hacer un resumen de lo que se ha avanzado, de los debates que estamos teniendo y de donde puedes echar una mano. Así no dependemos de que la gente se acuerde de meterse aquí ni de machacar por Twitter para que una mayoría lo lea.

¿Cómo lo veis? ¿Alguna idea mejor?

**Comment by rchavarria** [comment]
La idea de una newsletter me gusta como forma de _estar al tanto_, una especie de recordatorio semanal de lo que alguien se puede perder.

Para temas más estáticos o permanentes, me encanta el **blog**. Lo veo más fácil de navegar y de buscar información. También permite tener artículos que vayan evolucionando con el tiempo (se me ocurreo que podrían ser una especie de _seguimiento_ de algunas tareas/proyectos, aunque quizá para eso ya esté GitHub).

**Comment by JcMinarro** [comment]
Por qué no utilizar un canal de slack `Read Only` para ir anunciando lo nuevo, en plan newsletter??
Queda mucho más ordenado y no tienes que estar con el problema de  "Ahora mi newsletter me la marca cómo spam", "Ahora inbox me mete la newsletter en la agrupación blablabla"....

Para hacer un canal `Read Only` https://stacktodo.com/tools/block ;)

**Comment by fesja** [comment]
@rchavarria me parece bien lo del blog, ya sea propio o en Medium. Creo que para seguimiento de los proyectos más en detalle usaremos más Github.

@JcMinarro Slack es para chats y no todo el mundo quiere estar porque puede ser muy intenso (somos 30 en slack y hay más de 200 en twitter). Gracias por la sugerencia de todas maneras, no conocía esa integración!

**Comment by sergiocasero** [comment]
Creo que la mejor idea con diferencia para lanzar "noticias" a parte del propio github es un canal de Telegram, he creado telegram.me/codeforspain. Puede ser un simple canal de noticias para la gente que no quiera estar al tanto de Github o Slack, pero cuando salga un datasheet nuevo se pueda enterar rápidamente.

**Comment by fesja** [comment]
@sergiocasero puede ser! El tipo de comunicaciones que estaba pensando más eran del estilo:
- Necesitamos ayuda en X
- Acabamos de publicar este dataset o API
- Se va a organizar un meetup o evento

En el blog podemos escribir la noticia y luego enlazarlo en Telegram, pero es cierto que entonces es parecido a Twitter, no? Igual no hace falta... Simplemente tengo la sensación de que muchos no se enterarán hasta pasadas varias semanas de que necesitamos ayuda por ejemplo. ¿La gente prefiere recibirlo en el email o un canal de Telegram cerrado con solo anuncios, peticiones?

**Comment by sergiocasero** [comment]
La gran ventaja de telegram con respecto al resto es que es como "Whatsapp" y me explico:

Si tu(entiéndase como impersonal) pones un tweet, la gente puede verlo o no, lo mismo le pasa por el timeline sin pena ni gloria. Igualmente puede pasar con el blog, tu escribes un artículo y... ya está.

Telegram aporta el componente "push" que puede venir muy bien en este sentido. El canal puede ser público, se puede unir cualquiera con un enlace de invitación

PD: Hasta Errejón e Iglesias tienen un canal de telegram propio jaja, está extendida la práctica

**Comment by jgsogo** [comment]
¿Cuál es el enlace/invitación a slack? Me gustaría estar por ahí oyéndoos, aunque no sé si voy a tener tiempo para leer todo lo que escribáis ;D

**Comment by fesja** [comment]
pásame tu email !

**Comment by astrojuanlu** [comment]
¡Yo también quiero! Mi email está en mi perfil. Y por cierto @jgsogo saludos desde la otra mesa :wink:

**Comment by fesja** [comment]
@Juanlu001 @jgsogo @rchavarria @JcMinarro @sergiocasero al final hemos tirado por Discourse, es un foro muy majo y sirve como mailing list para que todos estemos al tanto de los nuevos comentarios y proyectos. Aquí os comparto algunos motivos del cambio http://comunidad.codeforspain.org/t/motivos-de-crear-este-foro/25. Esperamos vuestro feedback allí!
