### ISSUE TITLE
Dataset – Catastro

### ISSUE THREAD

**Issue by javaguirre** [codeforspain/datos#16]
Vamos a empezar con el estudio y obtención de datos del catastro, usaremos esta issue para ponernos de acuerdo todos los que queramos contribuir.

**Comment by javaguirre** [comment]
Enlace a la wiki: https://github.com/codeforspain/datos/wiki/Dataset-%E2%80%93-Catastro

**Comment by fpedrera** [comment]
Para esto, podéis contactar con las agrupaciones de Geoinquietos (http://geoinquietos.org/) y Open Street Map (http://www.openstreetmap.es/), que ya lo tienen trillado: 
- https://github.com/oscarfonts/catastro2postgis
- http://wiki.openstreetmap.org/wiki/ES:Cat2Osm2

**Comment by javaguirre** [comment]
Genial, pues eso podemos hacer. :-)

@fesja va a hablar también con una empresa que se dedica al tema, a ver si sacamos info más amigable para montar los datasets.

**Comment by fesja** [comment]
@javaguirre con los de openstreetmaps también tengo charla pendiente, habla si puedes con los de geoinquietos!

**Comment by javaguirre** [comment]
@fesja vale, me encargo de hablar con los geoinquietos.

**Comment by hhkaos** [comment]
@fesja @javaguirre , Jorge y Alberto son miembros activos de Geoinquietos tb :dancer:

**Comment by astrojuanlu** [comment]
Para cosas del catastro seguro que @tinproject puede echar una mano :) https://github.com/tinproject/pancat

**Comment by tinproject** [comment]
Sin problema, pero mi tiempo disponible a dos meses vista se mide en términos negativos :-(

Algún ratillo puedo sacar para revisar y asesorar. Lo primero es saber que información se quiere obtener de Catastro que no pueda hacerse de otras fuentes. La descarga de datos de la DGC se realiza con certificado digital (DNI electrónico) y está sujeta a una licencia especifica http://www.catastro.minhap.es/ayuda/lang/castellano/ayuda_descarga_cat.htm

**Comment by javaguirre** [comment]
Gracias por la info, creo que lo primero sería definir qué información pueden ser más interesante de recopilar como comenta @tinproject, por mi parte tengo que documentarme sobre ese tema.

¿Qué pensáis vosotros? ¿Qué información sobre el catastro consideraríais más relevante?

**Comment by javaguirre** [comment]
Hemos creado un [repositorio](https://github.com/codeforspain/ds-catastro) para ir recopilando el dataset como se ha comentado en [este hilo](https://github.com/codeforspain/datos/issues/17). La [wiki](https://github.com/codeforspain/datos/wiki/_Estructura-Repositorio-Dataset) tiene la información de cómo se van a ir estructurando estos repositorios.

Si os parece bien movemos todo lo relacionado con el catastro a este nuevo repositorio. Con respecto a mejoras sobre la estructura genérica de los repositorios podemos ir actualizando en la issue que he enlazado arriba o en la página de la wiki.

**Comment by javaguirre** [comment]
Hola,

he recopilado todos los datos comentados en este hilo y los he añadido en el repositorio del [catastro](https://github.com/codeforspain/ds-catastro/wiki).

Cierro esta issue si os parece y continuamos el debate allí con temas mas específicos de este dataset.
