### ISSUE TITLE
Proyecto en Github por cada Dataset

### ISSUE THREAD

**Issue by jgsogo** [codeforspain/datos#17]
Creo que es interesante debatir esta idea: **que cada dataset resida en un proyecto de Github independiente**.
# Ventajas:
- cada dataset/proyecto tiene un formato estándar común.
- página de bienvenida con información del dataset
- desarrollos relacionados con la estrategia ETL (se pueden configurar tests y tareas automatizadas con travis/appveyor)
- el propio dataset si está alojado (más sencillo seguir su trazabilidad) 
- colaboración y ruido: puedes suscribirte a proyectos concretos con los datos que te interesan, en vez de estar recibiendo notificaciones de todos.
# Desventajas:
- se divide la audiencia
- si no hay mucho movimiento es mejor concentrarlo para ver vidilla

¿Qué pensáis?

**Comment by jpaulet** [comment]
Totalmente de acuerdo. 

Se puede intentar evitar las 2 desventajas enlazando SIEMPRE en todos los repositorios al repositorio 'master' y así crear un flujo hacia el proyecto de "CodeForSpain", por ejemplo:

"Este repositorio X es parte del proyecto CodeForSpain (https://github.com/codeforspain) que ..."

O si un repositorio es muy pequeño, agruparlo a una categoria superior.

**Comment by sdemingo** [comment]
Yo también opino que separar repos por Datasets es la mejor forma de organizar el trabajo total y evitar el ruido excesivo que se puede generar si el tema va creciendo al ritmo de esta semana ;-)

**Comment by jgsogo** [comment]
Y otra ventaja muy importante que veo es que alguien puede añadir un _dataset_ a la iniciativa manteniendo su repositorio como _upstream_ para ese proyecto.

**Comment by fesja** [comment]
Decisión tomada entonces, creamos un repo por cada dataset! Me ha gustado como lo tienen en https://github.com/datasets. Os voy poniendo como miembros a los que os asignéis repos. Avisadme si me olvido.

He creado una página en el wiki con una [posible estructura para los repos](https://github.com/codeforspain/datos/wiki/_Estructura-Repositorio-Dataset) (he seguido el modelo del enlace anterior). ¿Cómo la veis?

**Comment by fesja** [comment]
ahora me entran dos dudas:
- el hilo donde resolvamos las dudas de un dataset estará en este repo central o en el propio repo del dataset
- la documentación del dataset (fuentes, comentarios, reflexiones) estará en el wiki de este repo o en el propio repo del dataset

Por cuestión de orden parece que tiene sentido que sea en cada repo aunque pueda hacer que se vean menos las dudas al estar separadas...

**Comment by jpaulet** [comment]
Yo optaría por resolver las dudas concretas de cada dataset en el propio repo, así no sobrecargamos a todo el mundo con pequeñas dudas o especificaciones.

Los comentarios generales se deben añadir aquí. 

Otra forma sería crear una issue por cada dataset, pero creo que sería extraño ya que en el dataset no habría información para otra gente que pueda entrar posteriormente. Creo que la reflexión es similar a la de "un repositorio" o "muchos"

**Comment by sdemingo** [comment]
Pienso igual, todo el trabajo del dataset incluidos docs, notas, dudas y comentarios al repo concreto. 

En el central debería publicarse lo que afecte o tenga que ser leido por todos.

**Comment by Worvast** [comment]
Veo razonable tener un dataset por repo, además fesja citas el de Github, creo que se debería de usar este, u otro aparte, como el de Github: un 'registro' (https://github.com/datasets/registry) con toda la información resumida de todos los datasets disponibles como:
- Nombre
- Url del proyecto en github
- Pequeña descripción (Que puede ser parte 'obligatoria' que necesita crear cada set para ser incluido en el registro, como la desc del repo)

Esto es porque, al final muchos problemas del OpenData es lo distribuido que está, y lo ideal existiendo este proyecto (En mi opinión) es que de un vistazo rápido puedas observar todos los datasets que hay con información rápida + url a ellos en una sola página (Y no el navegador de repors de una organización)

Al final cada dataset tendría sus issues/problemas, updates, dudas, etc mientras que el registro quedaría como información muy global de los datasets (Listado, estructuras que suelen ser bases, manifiesto, etc) y seguir llevando estas cuestiones.

Por aportar mi opinión :)

**Comment by fesja** [comment]
perfecto, estáis todo de acuerdo :)
- Un repo por cada dataset, y allí ponemos las issues y el wiki.
- En este repo hacemos el índice de datasets
