### ISSUE TITLE
Quiénes somos?

### ISSUE THREAD

**Issue by jpaulet** [codeforspain/datos#18]
Estaba pensando si sería una buena idea crear otra pàgina de la wiki con una lista de quien está colaborando en éste proyecto, principalmente por ir conociéndonos y poder seguirnos en twitter (por ejemplo) o poder saber quién es quién.

Habia pensado en algo muy senzillo del estilo:

> _Nombre de Persona_ - _@usuarioTwitter_ - (_correo@opcional.com_) - (_sitioWeb.com_) - usuarioGitHub 
> Pequeña descripción de empleo/estudio/etc. que pueda ser útil (ej: desarollador Ruby en Empresa.com y conocimientos de datos geo).

Os parece una buena idea? Ahora no es el momento?

A mí personalmente me gustaría poder saber un poco más de cada uno e incluso seguirlos en redes sociales (si el quiere, logicamente, si alguien quiere mantenerse anónimo no se añade nada y listo).

**Comment by sergiocasero** [comment]
Venga me animo:

Nombre: Sergio Casero 
Twitter: @sergioch23 
Email: sergio.casero23@gmail.com
Web: sergiocasero.es
Github: sergiocasero
Trabajo haciendo Android en Worldline.

Me he puesto con datos de CPs de momento :)

**Comment by fesja** [comment]
Parte de esa info está en Slack ya, cuando entres verás el canal #presentación :)
