### ISSUE TITLE
1er evento de comunidad

### ISSUE THREAD

**Issue by hhkaos** [codeforspain/datos#19]
Buenas familia, como comentaba por Slack voy a iniciar el issue para que los que queramos podamos debatir sobre este tema; resumo a grandes rasgos lo que comentaba. 

Mis propuestas de formatos serían:
1. Presentación de la comunidad + Desconferencia
2. Presentación de la comunidad + Hackathon

Imagino que tiene más sentido la primera, aunque apetece meterle mano a los datos...

Yo lo haría de 1 día completo.

Luego están las opciones de:
1. Hacer un evento presencial con streaming donde se pueda interactuar (Madrid/Barcelona)
2. Hacer múltiples eventos simultáneos, tantos como personas que quieran mojar, y luego poner aquí (en común) todo lo que salga de ellos, ya sea código, datos, ideas, etc.

> **Nota**: la opción 2) no quita que aquellas ciudades que quieran puedan hacer streaming también.

Yo creo que optaría por la segunda opción en ese caso; así es más abierto (como debe ser una comunidad, ¿no?)

¿Opiniones, ideas, propuestas?

**Comment by javaguirre** [comment]
> Presentación de la comunidad + Desconferencia

En el estado actual o a pocos meses vista veo esta opción más interesante. Creo que pueden salir más ideas de cómo recopilar los datos y hablar sobre los siguientes pasos que se podrían dar. La segunda creo que sería muy interesante también, pero más adelante.

> 1. Hacer un evento presencial con streaming donde se pueda interactuar (Madrid/Barcelona)
> 2. Hacer múltiples eventos simultáneos, tantos como personas que quieran mojar, y luego poner aquí (en común) todo lo que salga de ellos, ya sea código, datos, ideas, etc.

Como comentas veo más interesante la segunda, pero más difícil de realizar, de momento somos pocos y organizar eventos simultáneos lo veo imposible actualmente, ojalá me equivoque. :-)

Hacer la primera sería un objetivo no complicado, que nos serviría para compartir ideas y dar difusión a la iniciativa.

**Comment by hhkaos** [comment]
Gracias crack :)

Vamos a esperar un par de días a ver quién más da su opinión y vamos concretando.

Un abrazaco!

**Comment by calonso** [comment]
Estoy de acuerdo con @javaguirre. Ambas iniciativas son perfectas, pero quizás, para empezar sea mejor un pequeño encuentro, en plan meetup con una pequeña presentación de Code For Spain con dos objetivos:
1. Ponernos cara los que ya estamos dentro.
2. Darnos a conocer y reclutar a más gente.

Por supuesto darle difusión online para que todo el que viva fuera de la ciudad donde se haga el evento (Madrid?) pueda seguirlo es vital.

@hhkaos Cuenta conmigo para lo que necesites!

Un abrazo!

**Comment by Worvast** [comment]
Buenas, siendo breve creo que ponernos cara y debatiendo sobre las ideas que podemos tener, etc es la mejor manera de hacer un primer acercamiento, como han dicho, tipo Meetup a lo mejor también para darnos a conocer, y luego a quedarse a hablar.

Un Hackathon podría ser interesante mas adelante cuando se pudieran tener claras ms cosas sobre Code For Spain :D

**Comment by fesja** [comment]
Me parece bien lo que proponéis, un meetup con participación online para conocernos y sacar ideas. Y cuando estemos más asentados, organizar algo más grande.

Hoy he estado en Campus Madrid y me han dicho que contemos con ellos, les encanta la idea y le pueden dar difusión. Lo importante es que elijamos fecha para que bloqueen el auditorio. Podemos hacer dos cosas:
- meetup un dia por la tarde con participación online (podría ser en mayo)
- meetup un sábado entero (podría ser en junio me han dicho) donde gente de fuera de madrid pueda venir

**Comment by kinisoftware** [comment]
+1 al meetup!

Para que también lo tengáis en cuenta creo que no habría problema en usar las oficinas de Tuenti de Gran Vía ;) El aforo máximo para un meetup que no fuera hackatnon sería de 100 personas. Si hacemos hackathon ya cambia como distribuir todo y sería menos gente.

**Comment by vabada** [comment]
+1 al meetup y al meeting de un sábado entero
Genial para ponernos cara y alinearnos (yo estoy un poco perdido aunque me mola el dataset de los resultados electorales)

**Comment by sdemingo** [comment]
Yo votaría por la opción del sábado principalmente por los "raros" que como yo curran entre semana por la tarde/noche y estamos excluidos de la mayoría de los meetups :cry:

**Comment by hhkaos** [comment]
Cojonudo chicos :), pues vamos adelante con meetup online en Mayo y evento presencial en Junio 💃 

A mi la idea de campus me gusta porque además tiene una buena lista de difusión para que se entere más gente, aunque se agradece poder contar con las ofis de Tuenti tb @kinisoftware ^_^.

Hoy voy a estar currando por Campus, voy a ver si puedo reservar el auditorio ya para un sábado en Junio y así tenemos tiempo para darle difusión a esa jornada de ponernos cara en persona :); pero @sdemingo me temo que un meetup online previo será necesario también. Os paso luego un Doodle por aquí para tantear unas cuantas fechas, ahora me voy que tengo q pillar el coche para llegar a las 8:30 a  Madrid!.

Abrazo!

**Comment by fesja** [comment]
Tenemos novedades!

**Evento presencial**

@hhkaos lo ha movido y ya tenemos fecha y lugar:
- **Sábado, 18 de Junio de 9.00 a 16.00**
- Campus Madrid, la zona de cafetería, que viene muy bien para hacer una unconference

Ahora hay que ver qué formato hacemos, qué temas vamos a tratar allí, qué ideas vamos a explorar, qué vamos a enseñar, etc. Para prepararlo y hacer un resumen de voz, os proponemos hacer un meetup online en las próximas dos semanas.

¡Reservaros la fecha!

**Meetup online**
- Cuando: [a decidirse en este Doodle](http://doodle.com/poll/zm6cbipic5s2bpm8). Votar por favor con vuestro github username mejor.
- Qué herramienta a usar: opiniones?

**Temas a tratar en el evento**

Id comentando por aquí qué formato veis mejor (conferencia, unconference, temas definidos, temas abiertos) y temas o ideas que os gustaría que tratásemos entre todos.

**Comment by hhkaos** [comment]
Thx crack, respondido el Doodle!

En cto a herramientas propongo Skype o Hangout, ambas suelten ir bien, Hangout aunque me da más problemas permite mutear al resto, por el tema de posibles ruidos (que creo que skype no).

Yo creo que "unconference" es lo suyo, aunque podremos ir planteando una serie de temas previos por aquí (que con calma y desde casa se piensa con más claridad que con prisas), aunque luego allí se puedan proponer más y se elijan definitivamente cuales son los que se van a tratar allí (en función de quien vaya finalmente).

Podríamos empezar por los [temas que ya hay en los issues](https://github.com/codeforspain/datos/issues) y añadimos cualquier otro que nos parece interesante, ¿no?.

Eso sí, yo me centraría en problemáticas generales, no tanto de crear/normalizar datasets concretos, ¿no?

**Comment by fesja** [comment]
Pensando en alto, veo diversos temas interesantes:
- Cómo difundir Casos de Exito de Datos Abiertos
- Formatos y vocabularios comunes de datasets
- Brainstorming de Web y Apps que podemos hacer
- Brainstorming de Datasets que sería interesante reformatear o liberar
- Si vienen responsables públicos, una sesión para escuchar su forma de trabajar, lo que han conseguido y sus problemáticas
- Podemos ir también por verticales: educación, tráfico, medio ambiente, sanidad...
- Podemos ir también por ciudades vs comunidades vs estado

Estoy de acuerdo en que Unconference puede ser el mejor formato, yo creo que al final el evento puede ser un día de brainstorming general, de escuchar ideas y proyectos que se intentaron. Es como un kick-off de Code for Spain.

**Comment by fesja** [comment]
@hhkaos @calonso @javaguirre @hhkaos @Worvast @kinisoftware @abadabanades @sdemingo he creado un hilo sobre el evento en el nuevo foro http://comunidad.codeforspain.org/t/primer-evento-de-code-for-spain-18-de-junio/19. Por favor, añadid vuestros comentarios ahí sobre lo que podemos hacer.
