### ISSUE TITLE
Valenbisi: Servicio publico de alquiler de bicicletas en Valencia

### ISSUE THREAD

**Issue by quiqueporta** [codeforspain/datos#2]
API publica.

**Ubicación de las estaciones**:
http://www.valenbisi.es/service/carto

**Detalle de una estación**:
http://www.valenbisi.es/service/stationdetails/valence/{num_estacion}

**Comment by jalbertoroman** [comment]
Gracias! puedes añadirlo tú mismo al wiki para ir más rápido. :smile:

**Comment by quiqueporta** [comment]
Si.
