### ISSUE TITLE
¿Unificar nombres de población y otros datos?

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#22]
Buenas,

Una duda que me ha surgido es cómo asegurar que los nombres de poblaciones de los datos de Población coinciden con los datos de Límites administrativos o de Desempleo. Puede suceder que en uno aparezca como "A Coruña" y en otro como "La Coruña" o "Coruña, A " por ejemplo. O que por fallo de la fuente, falten algunos.
- ¿Al sacar los datos, el responsable de un repo debería comprobar que contengan el mismo número de poblaciones y coincidan los nombres?
- ¿Qué hacer si no coinciden?

Ahora mismo no estamos uniendo los datos de diversos repos, pero ya que estamos, igual podemos tenerlo en cuenta. ¿Cómo lo veis?

**Comment by jalbertoroman** [comment]
¿Habrá que poner un ID y nombres alternativos?

**Comment by inigoflores** [comment]
Siempre que tengamos el codigo INE, el campo nombre se puede obviar. En su lugar, se referencia mediante clave externa una tabla 'maestra' (municipios, provincias, etc.) que incluya la denominación en las distintas variantes (oficial, castellano, lengua regional, etc.). Puede interesar incluso añadir una columna para ingles (Seville, Navarre, Biscay, etc.) u otros idiomas.

Esto me recuerda que no hemos previsto un Dataset que se centre exclusivamente en proporcionar estos datos, que son en mi opinión bastante prioritarios, pues sirven de base para construir otros.

**Comment by jalbertoroman** [comment]
No me gusta tener una tabla de claves, creo que cada dataset debería ser autocontenido, autoexplicativo y relacionales entre si. 
La tabla puede ser de consulta para nosotros y para los usuarios, pero no lo debería ser imprescindible. Es un problema que me encuentro habitualmente. Muchos códigos que no sabes de dónde vienen y tienes que bucear en la documentación hasta que lo encuentras.

**Comment by inigoflores** [comment]
Es opcional, por supuesto. No hablo de eliminar la información de nombre, sino dar la opción de descargar otra tabla con información adicional. Más que nada por lo de intentar tener la base de datos lo más normalizada posible.

Por ejemplo:
- En **ds_población** tenemos el campo `ine_code`.
- En **ds-limites-administrativos** tenemos `NATCODE`, de donde se puede extraer el código INE: 
  
  ```
  "NATLEVEL": "4thOrder", "NATCODE": "34053535026", "NAMEUNIT": "Telde", 
  ```

La clave externa referencia la clave primaria de la tabla maestra (municipios, provincias, etc.), que coincide con el código INE. No estoy hablando de usar un nuevo `id` creado por nosotros.

Así mismo, es la única manera de saber si los datos están completos, o si -por el contrario- falta algo (p.e. los municipios de nueva creación).

**Comment by fesja** [comment]
> Esto me recuerda que no hemos previsto un Dataset que se centre exclusivamente en proporcionar estos datos, que son en mi opinión bastante prioritarios, pues sirven de base para construir otros.

+1, ¿lo sacamos del INE? Si es así, @ferblape está con un script que nos permitirá sacar la lista de municipios de la lista oficial. ¿o ya está en CSV/JSON/GeoJSON?

Respecto al ID:
- De acuerdo en usar el ine_code.
- De acuerdo en mantener el nombre de la población/provincia en cada dataset
- Podemos requerir que todo dataset que referencie a zonas administrativas contenga el ine_code para poder enlazar bien.
- Otra duda es si en `ds-poblacion` solo poner el ine_code del muncipio o también el ine_code de la provincia/comunidad para poder filtrar. Realmente con el repo oficial de Municipios de coge rápido el código de provincia y se puede filtrar rápido.

**Comment by ferblape** [comment]
Hola!

Creo que es vital que todo dataset tenga al menos el código del INE para poder cruzarlo, sin eso es prácticamente inútil. El nombre no lo veo tan prioritario, porque puede haber datasets que tengan nombres diferentes (lo digo porque algunos incluyen por ejemplo el nombre en castellano / nombre en segunda lengua, y otros no). 

Los códigos del INE los tenemos en la gema [ine-places](https://github.com/populatetools/ine-places), en la carpeta [data](https://github.com/PopulateTools/ine-places/tree/master/lib/ine/places/data).

Los hemos sacado desde estos dos links:

http://www.ine.es/daco/daco42/codmun/codmun11/11codmunmapa.htm
http://www.ine.es/jaxi/menu.do?type=pcaxis&path=/t20/e245/codmun&file=inebase&L=0

**Comment by inigoflores** [comment]
@fesja: de acuerdo en todo. Con respecto al código INE de municipio, éste lleva implícito el código de la provincia (2 primeros dígitos). De hecho es como aparece en la fuente oficial.

![Listado Municipios INE](http://i.imgur.com/ZVkZ8yY.png)

@ferblape: buen trabajo con la gema ine-places! Veo que es un práctico wrapper para archivos .csv, pero no veo que incluya un script de descarga de los datos (no me parece haberlo visto).

Lo que propongo es crear un nuevo dataset que se centre en gestionar la información sobre organización territorial, y que incluya:
- Autonomías 
- Provincias
- Municipios 
- Poblaciones y Localidades 
- Islas por provincia 
- Municipios por Isla 
- Comarcas?
- Demarcaciones y Partidos Judiciales?

Todo ello con sus códigos INE, sus códigos MHAP y en varios idiomas. Lo tengo empezado en https://github.com/inigoflores/spanish-administrative-data. Está en PHP, pero puedo pasarlo a otro lenguaje si hiciera falta. Los municipios se actualizan todos los años, y el INE ofrece un histórico que podemos incluir también.

¿Qué os parece?

**Comment by ferblape** [comment]
Efectivamente, no tiene nada para descargar los datos y actualizarlos. Al ser una gema, la idea es ir lanzando versiones de la gema según se actualicen los datos en el INE.

**Comment by fesja** [comment]
Ok, entonces parece que con incluir el código INE del municipio vale. Ya incluye la provincia.

@inigoflores adelante con el dataset! Partiendo de lo que estamos hablando aquí, ¿cómo dejarías los JSON? ¿Abres un dataset y comentas en una issue el formato para acordarlo antes de que te pongas a picar?

gracias!

**Comment by inigoflores** [comment]
Genial! Me parece buena idea crear el repo y abrir un issue para pedir feedback.

Sugerencias para el nombre:
- ds_organizacion_territorial
- ds_organizacion_administrativa
- ds_divisiones_administrativas

¿Alguna preferencia? ¿Otra?

**Comment by fesja** [comment]
ya tenemos ds-limites-administrativos asi que puede ser
ds-organizacion-administrativa

**Comment by fesja** [comment]
@inigoflores cierro esta issue, estamos pendientes de dar feedback en tu repo. Gracias!

**Comment by inigoflores** [comment]
@fesja: Perfecto! Mañana me pongo con ello. ¿Creas tú el repo **ds-organizacion-administrativa**? Creo que no tengo privilegios.
