### ISSUE TITLE
¿Cómo indicar la fecha en los datasets?

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#24]
Viendo el trabajo de @calonso en https://github.com/codeforspain/ds-empleo (gracias!!), saco varias dudas de cara a que lo hablemos y homogeneizemos. Deberíamos hacer igual que hacen los mejores datasets o las normas. Igual por algún enlace de los que nos hemos cruzado ya lo comentan.

[CSV Nivel España](https://github.com/codeforspain/ds-empleo/blob/master/data/national.csv)
- ¿Dejamos que el Periodo sea `2015T4` o lo separamos en dos campos `Año: 2015` y `Trimestre: 4`?

[JSON Nivel España](https://github.com/codeforspain/ds-empleo/blob/master/data/national.json)
- ¿El campo `created_at` lo dejamos así suelto o debería ir los datos dentro de un `data`?
- ¿Debería estar la clave `2015T4` o no debería haber clave y en cambio ser un campo o varios (Año, Trimestre) dentro de cada objeto?

[JSON Nivel Comunidades](https://github.com/codeforspain/ds-empleo/blob/master/data/autonomous_communities.json)
- ¿Debería estar las claves `Andalucía` y luego `2015T4` o deberían ser campos de cada objeto? Ejemplos:

```
"Andalucía": {
    "2015T4": {
      ...
   },
   ...
}
```

o

```
{
      "Comunidad": "Andalucía",
      "Periodo": "2015T4",
      "Total": 6879800,
      "Activos": 4017700,
      "Ocupados": 2819400,
      "Parados": 1198300,
      "Parados que buscan primer empleo": 108000,
      "Inactivos": 2862200
}
```

Aparte, parece que vamos a tener que meter el INE code, tal y como estamos hablando en esta issue #22

**Comment by esebastian** [comment]
Respecto al tema del periodo pienso que podríamos separarlo, quizá del mismo modo que hace la AEAT: 'año': 2015, 'periodo': '4T'

En cuanto al `created_at`, no tengo claro que aporte mucho ahí. Yo lo vería en el `last_updated` del `datapackage.json`.

Y con la estructura del JSON yo iría a lo segundo, que es lo que entiendo tiene más sentido a la hora de utilizar los datos programáticamente porque define una estructura basada en descriptores y similar para todos los registros. En cualquier caso creo que habría que revisar el valor de las claves del JSON para que se ajusten a un formato estándar (camel case, snake case, uso de caracteres especiales, etc). ¿Al final se aceptaba como guía https://project-open-data.cio.gov/v1.1/schema/? ¿Las claves las escribimos en español o en inglés?

**Comment by calonso** [comment]
Buenas,

Respecto a  los metadatos (`created_at`, ...) había pensado en crear un nuevo archivo `nombrearchivo.meta` o algo así para añadirlos, pero parece buena idea, @esebastian,  ponerlo en el `datapackage.json`.

Respecto a la estructura del JSON, me parece buena idea la de declarar un `schema` como propone @fesja. A ver si saco un ratillo y añado esas dos mejoras.

**Comment by javaguirre** [comment]
100% de acuerdo con @esebastian 

Con respecto a las claves también creo que tenemos que estandarizar cómo se especifican los atributos/campos (no tengo ni idea de cuál sería el mejor formato, no he leído el enlace que ha puesto @esebastian arriba todavía).

Con respecto al idioma, yo lo haría en castellano, ya que son datos de España y su mayor uso sería para usuarios de lengua castellana, por defecto nos ahorraríamos la i18n en caso de uso para lengua española. Se puede hacer una versión con los campos traducidos más adelante si se requiere.

**Comment by inigoflores** [comment]
> ¿Dejamos que el Periodo sea 2015T4 o lo separamos en dos campos Año: 2015 y Trimestre: 4?

Yo no lo separaría en dos campos, pero sí que intentaría pasarlo a un formato de fecha fácil de leer por una máquina y reconocible por un usuario que no hable español (en inglés se usan cosas como _Q1 2014_ or _Q1/14_). Podría ser el primer día del trimestre (si siempre vamos a trabajar con trimestres):

```
2015T4 = 2015-10-01
```

También está la opción de usar el formato definido por ISO 8601:

```
2015T4 = 2015-10-01/P3M
```

Ver esta respuesta de S.O: http://stackoverflow.com/a/5709503/3144159

> ¿Debería estar la clave 2015T4 o no debería haber clave y en cambio ser un campo o varios (Año, Trimestre) dentro de cada objeto?

No es buena idea usar una clave de este tipo, principalmente por que -a la hora de decodificar el JSON- va a crear un objeto con propiedades que empiezan con números, lo que no está permitido en la mayoría de los lenguajes de programación.

Yo transformaría la clave en una nueva columna, como sugiere @fesja. 

> ¿Debería estar las claves Andalucía y luego 2015T4 o deberían ser campos de cada objeto? 

Aquí lo mismo, sería conveniente pasar las claves a sus correspondientes columnas. Pero además del nombre haría falta incluir el código INE de la C.A / provincia o municipio.

> En cuanto al created_at, no tengo claro que aporte mucho ahí. Yo lo vería en el last_updated del datapackage.json.

Si se incluye en el JSON como metadato (yo casi lo prefiero), esta información debe separarse de los datos. Una posible estructura puede ser la de un objeto que incluya dos propiedades: la fecha de creación y un array de registros encapsulados en objetos. Sería algo así:

```
{
    "created_at": "2016-04-17 21:15:51 +0200",
    "data" : [
        {
            "Total": 326700,
            "Activos": 189700,
            "Ocupados": 148000,
            "Parados": 41700,
            "Parados que buscan primer empleo": 4800,
            "Inactivos": 137000,
            "Provincia": "Albacete",
            "Trimestre": "2015T4"
        },
    [...]
    ]
}
```

Otra opción es incluirlo como una columna más y dejamos el fichero plano, pero quizás añade demasiada información redundante.

> Con respecto a las claves también creo que tenemos que estandarizar cómo se especifican los atributos/campos

Cuando no se pueda respetar los nombres originales de las variables (como es el caso), tocará transformarlos en algo que puedan entender las máquinas.

Para JSON  tengo por costumbre usar el formato con underscore típico de C ó SQL. Aunque Google recomienda usar camel case. Me da igual. Me adapto a lo que prefiera la mayoría. Echadle un vistazo a esta pregunta de S.O. : [JSON Naming Convention](http://stackoverflow.com/q/5543490/3144159).

Como idioma prefiero el inglés, pues suele ser más compacto. Ejemplo:

```
parados_que_buscan_un_primer_empleo 
```

vs

```
unemployed_first_job_seekers
```

También es más universal.

**Comment by fesja** [comment]
Estamos de acuerdo en lo siguiente:
- Mover `created_at` al fichero `datapackage.json`
- Aplanar los arrays, la fecha y comunidad irán como atributo. Asi es igual al CSV ya de paso.
- Meteremos el código INE tal y como decidamos en #22 

Mi opinión en lo siguiente:
- Yo separaría Año y Trimestre, queda más claro y es como se suele poner. Asi es más fácil filtrarlo en Tableau por ejemplo.
- En CSV pondremos los headers en español.
- En JSON tendría sentido que también estuvieran en Español. Aunque si queremos seguir algún estandar internacional debería estar en inglés.
- En cualquier caso yo me inclino también a usar underscore para las claves ([Google usa underscore](https://developers.google.com/places/web-service/details#PlaceDetailsResponses) @inigoflores).
- No he encontrado ninguna web donde compartan los nombres de las claves del JSON. ¿Sabéis si hay algo? El otro día hablé con Oscar Corcho (UPM) y me dijo que estaban trabajando en ello, y en unas semanas me diría algo para ponernos de acuerdo.
- En JSON, si un atributo está vacío, no añadirlo o poner null. No poner "".

**Comment by inigoflores** [comment]
> En cualquier caso yo me inclino también a usar underscore para las claves (Google usa underscore @inigoflores).

Se ve que no predican con el ejemplo :)
- [Google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml)

> En JSON, si un atributo está vacío, no añadirlo o poner null. No poner "".

Por lo que tengo entendido:
- `""` representa que el atributo no es relevante.
- `null` representa que el valor del atributo no es conocido.

Esto puede ser un problema si la fuente establece distinción semántica entre ambos, y los usa en el mismo dataset para referirse a circunstancias diferentes. Estaríamos descartando información unificando ambos valores.

Ver [When to use NULL and when to use an empty string?](http://dba.stackexchange.com/questions/59/when-to-use-null-and-when-to-use-an-empty-string)

Perfecto por todo lo demás!

**Comment by fesja** [comment]
He metido todo en esta página del wiki https://github.com/codeforspain/datos/wiki/_Estructura-Repositorio-Dataset

**Comment by ocorcho** [comment]
Perdón por meter un comentario en un issue ya cerrado, pero no he podido mirarlo hasta ahora. Otra opción que puede ser interesante, y que yo uso en todos mis datasets, es la de usar este servicio: https://datahub.io/dataset/data-gov-uk-time-intervals (que está siempre online y da muchos metadatos sobre cada periodo).
