### ISSUE TITLE
RAE

### ISSUE THREAD

**Issue by javierhonduco** [codeforspain/datos#3]
No sé muy bien cómo añadir esto en la wiki ya que no hay tal categoría, así que díganme! :grin: 

Hay varios proyectos relacionados:
[https://github.com/raul/rae-downloader](https://github.com/raul/rae-downloader) para descargar las palabras hecho por @raul
[https://github.com/javierhonduco/nebrija](https://github.com/javierhonduco/nebrija) para acceder a la rae que hice yo

Decidme qué os parece! :smile:

**Comment by fesja** [comment]
añadidos al final en la categoría Otros! gracias javier
