### ISSUE TITLE
¿Reformatear o enlazar a la fuente original?

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#8]
Ayer hicimos un hangouts rápido entre varios y este fue un tema de los que salió. ¿El objetivo de este primer proyecto de CodeForSpain es coger todas las fuentes, reformatearlas y meterlas en una base de datos única o es hacerlo solo con aquellas difíciles de conseguir o con un formato no amigable?

El problema de pensar en todas las fuentes es que el trabajo es inmenso, sobre todo si las reformateamos para que sigan nuestros estándares, y luego hay que actualizarlas. Sería un poco duplicar el trabajo de http://datos.gob.es/.

Yo creo que al menos en un estado inicial deberíamos enlazar si la fuente está bien o reformatear y alojar nosotros si es mejorable o no existe. ¿Qué opináis?

**Comment by fesja** [comment]
tests

**Comment by amfeli** [comment]
Enlazar a la fuente si esta es estable como, por ejemplo, la del Centro de Descargas del CNIG http://centrodedescargas.cnig.es/CentroDescargas/catalogo.do#selectedSerie teniendo en cuenta que la cantidad de información es monumental. Imaginaos tener que descargar y servir las imágenes de España tomadas por satélites, estamos hablando de Petabytes.

**Comment by inigoflores** [comment]
> Yo creo que al menos en un estado inicial deberíamos enlazar si la fuente está bien o reformatear y alojar nosotros si es mejorable o no existe. ¿Qué opináis?

Totalmente de acuerdo. Por ejemplo, fuentes candidatas son todas aquellas que se ofrecen en Excel.

**Comment by iblancasa** [comment]
Yo creo que lo suyo es reformatear siempre que la fuente no sea un formato "estándar" o alguna porquería como Excel.
Por supuesto, SIEMPRE, citar la fuente.

**Comment by fesja** [comment]
Decisión tomada: Si la fuente original está en un formato estándar, enlazaremos; si no, reformatearemos. Esto lo tendremos que decidir caso por caso para tener claro qué consideremos una fuente como válida.
