### ISSUE TITLE
¿Cómo actualizar los datos?

### ISSUE THREAD

**Issue by fesja** [codeforspain/datos#9]
Este es otro tema espinoso. Suponiendo que reformateamos y alojamos todos los datos porque lo hacemos con todas o porque estas fuentes son mejorables:
- Si cogemos la lista de playas por ejemplo, todos los años la actualizan para reflejar las banderas azules nuevas. Por tanto habría que actualizarla cada año (o varias veces). 
- Si cogemos la lista de farmacias, posiblemente hay que hacerlo cada semana.
- Si cogemos el nivel de la polución en Madrid, habrá que hacerlo cada día. 

¿Cómo enfocamos las actualizaciones? Se me ocurre:
- Para aceptar un tipo de datos que alojemos, no solo pedimos los datos si no el script que los actualice.
- Pedimos el script con las instrucciones que se ejecute manualmente
- No hacemos nada, y mostramos la fecha de última actualización (esta queda descartada)

Obviamente depende de cada tipo de fuente, pero por ir pensando en donde ponemos nuestro nivel de calidad.

**Comment by amfeli** [comment]
En datos geográficos no suele haber scripts. Lo que se hace es incluir la fecha en los metadatos. Estos metadatos suelen estar en el estándar ISO 19100 pero, por experiencia propia, rellenar correctamente ese formato es un trabajo ingente. Yo uso un estándar Dublin Core en el lugar que comenté en otro hilo http://secad.unex.es/conocimiento/ Insisto en que hablo sólo de información cartográfica.

**Comment by inigoflores** [comment]
Creo que es fundamental tener acceso a los scripts que actualizan los datos. En función de la frecuencia de actualización de cada fuente, se pueden crear tareas `cron` a medida que mantengan al día copias locales de los datos. 

He recopilado algunos scripts que tenía en https://github.com/inigoflores/spanish-administrative-data. A ver qué os parece.

**Comment by fesja** [comment]
@inigoflores vaya fiesta tienen en el catrasto + INE!! Añado el enlace al wiki. Gracias por compartir!

**Comment by tinproject** [comment]
No se si conocéis los Notebooks de Jupyter (http://jupyter.org), es una buena manera de compartir el código utilizado para una tarea de forma documentada y repetible para que cualquiera pueda seguir proceso utilizado para obtener y transformar los datos.

**Comment by iblancasa** [comment]
@tinproject para eso creo que es mejor la plataforma que estamos utilizando ahora. Entre el uso de markdown y el tipo de documentación que utilice el propio lenguaje... creo que se puede hacer algo bastante decente sin tener que usar tantas cosas distintas.

Yo voto por la opción "Pedimos el script con las instrucciones que se ejecute manualmente"

**Comment by fesja** [comment]
Decisión tomada: Si reformateamos los datos, necesitamos el script documentado para poder volver a ejecutarlo y reformatear los datos actualizados.
